# Generated by Django 3.2.9 on 2021-11-19 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.user')),
                ('stud_name', models.CharField(max_length=30)),
                ('email', models.EmailField(default='', max_length=254)),
                ('branch', models.CharField(choices=[('CSE', 'Computer Science'), ('ECE', 'Electronics'), ('BIO', 'Bio-medical'), ('DSE', 'Datascience'), ('GEN', 'Generic')], default='GEN', max_length=3)),
                ('student_profile_pic', models.ImageField(blank=True, default='img.png', upload_to='profile_pics')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.user')),
                ('teacher_name', models.CharField(max_length=30)),
                ('contact_number', models.CharField(max_length=10)),
                ('email', models.EmailField(default='', max_length=254)),
                ('teacher_profile_pic', models.ImageField(blank=True, default='img.png', upload_to='profile_pics')),
                ('designation', models.CharField(max_length=300)),
                ('branch', models.CharField(choices=[('CSE', 'Computer Science'), ('ECE', 'Electronics'), ('BIO', 'Bio-medical'), ('DSE', 'Datascience'), ('GEN', 'Generic')], default='GEN', max_length=3)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
