# Generated by Django 3.2.9 on 2021-11-25 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_response_responsesheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsesheet',
            name='correct',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='responsesheet',
            name='score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='responsesheet',
            name='wrong',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
