# Generated by Django 3.2.9 on 2021-11-25 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20211125_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsesheet',
            name='correct',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='responsesheet',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='responsesheet',
            name='wrong',
            field=models.IntegerField(default=0),
        ),
    ]
